### ISSUE TITLE
For IOS

### ISSUE THREAD

**Issue by alimimert** [VaishnavDatir/sql_conn#16]
When will the update for ios come ?
or can i make it compatible for IOS by adding myself ?

**Comment by VaishnavDatir** [comment]
Hi @alimimert,
Thanks for using sql_conn & waiting for this long.
But due to some reason I'm not looking after ios release. 
Update from my side: Currently, I'm looking on stored procedures and parameterized query. Also some performance fix & other functionality. 

Answer to your other question, yes you can make it compatible for iOS by adding yourself. You can also raise a Pull Request. Collaborators are always welcome. 

Thankyou

**Comment by VaishnavDatir** [comment]
Hi @alimimert,

iOS support wont be possible now.
But sure in future will work on it.

Thanks
